---
# roles/prom_gw/defaults/main.yml
# 角色默认变量(可被 inventory 或 -e 覆盖)。
prom_gw_release_dir: /opt/prom-gw
prom_gw_config_dir: /etc/prom-gw
prom_gw_wal_dir: /data/wal
prom_gw_log_dir: /var/log/prom-gw
prom_gw_user: promgw
prom_gw_group: promgw
prom_gw_base_port: 19201
prom_gw_metrics_port: 8080
prom_gw_health_port: 8081
prom_gw_admin_port: 8082
prom_gw_admin_allow_cidr: "127.0.0.1/32,10.0.0.0/8"
prom_gw_kafka_brokers: ""
prom_gw_nacos_addr: ""
